'use strict';
const fs=require('node:fs'),path=require('node:path'),os=require('node:os'),assert=require('node:assert/strict');
const {app,Menu,dialog}=require('electron');
const directory=fs.mkdtempSync(path.join(os.tmpdir(),'rixu-language-ui-'));
process.env.RIXU_DATA_DIR=directory;process.env.RIXU_TEST='1';
const {Store}=require('../src/store.cjs');
const seed=new Store(directory);
seed.saveSettings({quickShortcut:'Alt+Shift+Space'});
const title='今天 · 马上做 <img src=x> {0}',notes='已完成 · untouched notes';
const id=seed.create({title,notes,due:new Date(Date.now()+35*3600000).toISOString(),plannedDate:require('../src/renderer/time.js').dateKey(new Date())});
const before=seed.snapshot().tasks;
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
async function until(fn,label){for(let i=0;i<100;i++){if(await fn())return;await sleep(50);}throw Error('Timeout: '+label);}
(async()=>{
 const runtime=await require('../src/main.cjs').start(),win=runtime.window;win.show();
 const js=code=>win.webContents.executeJavaScript(code,true);
 const call=(name,payload)=>js(`window.fourfold.call(${JSON.stringify(name)},${JSON.stringify(payload)})`);
 await until(()=>js('document.querySelectorAll(".zone").length===4'),'board');
 await js('document.querySelector("#settings-button").click()');
 await js('const language=document.querySelector("[data-setting=language]");language.value="en";language.dispatchEvent(new Event("change",{bubbles:true}));');
 await until(()=>js('document.documentElement.lang==="en-US"'),'English switch');
 assert.equal(runtime.store.state.settings.language,'en');
 assert.equal(await js('document.querySelector("#settings-title").textContent'),'Settings and backup');
 assert.equal(await js('document.title'),'Rixu');
 assert.match(await js('document.querySelector(".due").textContent'),/Due in/);
 assert.equal(await js('document.querySelector(".task-title").textContent'),title);
 assert.equal(await js('document.querySelector("#task-title").placeholder'),'What needs doing?');
 await js('document.querySelector("#settings-dialog").close()');
 for(const view of ['today','week','inbox','quadrants']){
   await call('settings',{view,calendarOpen:true});
   assert.deepEqual(await js('window.RixuI18n.missing()'),[],view+' translation coverage');
 }
 assert.match(await js('document.querySelector(".month-heading").textContent'),/[A-Za-z]/);
 assert.equal(await js('document.querySelectorAll("#lock-panel,#minimize,#close-window").length'),0);
 await js(`document.querySelector('[data-edit="${id}"]').click()`);
 await until(()=>js('document.querySelector("#task-dialog").open'),'editor');
 await js('document.querySelector("#task-notes").value="未保存的内容"');
 await call('settings',{language:'zh-CN'});await call('settings',{language:'en'});
 assert.equal(await js('document.querySelector("#task-notes").value'),'未保存的内容');
 assert.equal(await js('document.querySelector("#task-title").value'),title);
 assert.equal(await js('document.querySelector("#task-dialog-title").textContent'),'Task details');
 await js('document.querySelector("#task-dialog").close()');
 await runtime.showQuickCapture();const quick=runtime.getQuickWindow();
 await until(()=>quick.webContents.executeJavaScript('document.documentElement.lang==="en-US"'),'quick English');
 assert.equal(await quick.webContents.executeJavaScript('document.querySelector("#quick-title").placeholder'),'Capture a thought…');
 await quick.webContents.executeJavaScript('document.querySelector("#quick-title").value="今天 draft"');
 await call('settings',{language:'zh-CN'});
 await until(()=>quick.webContents.executeJavaScript('document.documentElement.lang==="zh-CN"'),'quick Chinese');
 assert.equal(await quick.webContents.executeJavaScript('document.querySelector("#quick-title").value'),'今天 draft');
 assert.equal(await quick.webContents.executeJavaScript('window.fourfold.call("state").then(()=>false).catch(()=>true)'),true);
 await call('settings',{language:'en'});await call('quick:hide');
 const invalid=await js('window.fourfold.call("create",{title:""}).catch(e=>e.message)');assert.equal(invalid,'Enter a task title');
 let prompt;const original=dialog.showMessageBox;dialog.showMessageBox=async(_win,options)=>{prompt=options;return {response:0};};
 await call('purge',{id});dialog.showMessageBox=original;assert.equal(prompt.message,'Permanently delete this task?');assert.deepEqual(prompt.buttons,['Cancel','Delete permanently']);
 if(process.platform==='darwin')assert.equal(Menu.getApplicationMenu().items[1].label,'Edit');
 assert.deepEqual(runtime.store.snapshot().tasks,before);
 const restored=new Store(directory);assert.equal(restored.state.settings.language,'en');assert.deepEqual(restored.state.tasks,before);
 assert.deepEqual(await js('window.RixuI18n.missing()'),[]);
 assert.deepEqual(await quick.webContents.executeJavaScript('window.RixuI18n.missing()'),[]);
 await call('update',{id,patch:{title:'Review this week’s plan'}});
 await call('settings',{calendarOpen:false,desktopBlend:true});
 const artifacts=process.env.RIXU_ARTIFACTS_DIR||path.join(directory,'artifacts');fs.mkdirSync(artifacts,{recursive:true});
 win.show();win.focus();await sleep(400);
 fs.writeFileSync(path.join(artifacts,'english-planner.png'),(await win.webContents.capturePage()).toPNG());
 await js('document.querySelector("#settings-button").click()');await sleep(400);
 fs.writeFileSync(path.join(artifacts,'language-settings.png'),(await win.webContents.capturePage()).toPNG());
 const result={passed:true,platform:process.platform,arch:process.arch,version:require('../package.json').version,checks:['live Chinese/English switch','all planner views and calendar','static editor and settings','quick capture live switch and draft retention','request isolation','localized validation and native dialog','task and draft preservation','persisted language after reopen']};
 fs.writeFileSync(path.join(artifacts,'language-test.json'),JSON.stringify(result,null,2));console.log(JSON.stringify(result));app.quit();
})().catch(e=>{console.error(e);app.exit(1);});
