'use strict';
const fs=require('node:fs'),path=require('node:path'),os=require('node:os'),assert=require('node:assert/strict');
const {app,globalShortcut}=require('electron');
const dir=fs.mkdtempSync(path.join(os.tmpdir(),'rixu-desktop-'));
process.env.FOURFOLD_DATA_DIR=path.join(dir,'data');process.env.FOURFOLD_TEST='1';
const {Store}=require('../src/store.cjs'),{dateKey,weekDays}=require('../src/renderer/time.js');
const seed=new Store(process.env.FOURFOLD_DATA_DIR),today=dateKey(new Date()),days=weekDays(),due=new Date(Date.now()+35*3600000).toISOString();
const a=seed.create({title:'完成产品方案',level:1,due,plannedDate:today,estimatedMinutes:90});
const b=seed.create({title:'阅读一章书',level:2,plannedDate:today,estimatedMinutes:30});
const c=seed.create({title:'整理桌面文件',level:3,plannedDate:today,estimatedMinutes:15});
const d=seed.create({title:'预约牙科检查',level:2,plannedDate:today,estimatedMinutes:10});
seed.create({title:'做一份秋日旅行清单',inbox:true,level:3});seed.create({title:'下周的读书分享',inbox:true,level:3});
seed.plan(a,{day:today,focus:true});seed.plan(b,{day:today,focus:true});
seed.create({title:'确认设计交付',level:0,plannedDate:days[0],estimatedMinutes:120});seed.create({title:'集中写作',level:2,plannedDate:days[2],estimatedMinutes:420});
const late=seed.create({title:'回复合作邮件',level:0,due:new Date(Date.now()-3600000).toISOString(),plannedDate:today,estimatedMinutes:15});
seed.saveSettings({theme:'light',view:'today',transparency:15,quickShortcut:'Alt+Shift+Space'});
const sleep=ms=>new Promise(r=>setTimeout(r,ms));async function until(fn,label){for(let i=0;i<100;i++){if(await fn())return;await sleep(30);}throw Error('Timeout: '+label);}
(async()=>{
 const runtime=await require('../src/main.cjs').start(),win=runtime.window,s=runtime.store;win.show();
 const js=x=>win.webContents.executeJavaScript(x,true),call=(name,payload)=>js(`window.fourfold.call(${JSON.stringify(name)},${JSON.stringify(payload)})`);
 const errors=[];win.webContents.on('console-message',(_e,detail)=>{if(detail.level==='error')errors.push(detail.message);});
 await until(()=>js('!!document.querySelector(".focus-grid")'),'today');
 assert.equal(await js('document.querySelectorAll(".focus-grid .task").length'),2);
 await js(`document.querySelector('[data-focus="${c}"]').click()`);await until(()=>Promise.resolve(s.state.tasks.find(t=>t.id===c).focusDay===today),'star third');
 await js(`document.querySelector('[data-focus="${d}"]').click()`);await sleep(150);assert.equal(s.state.tasks.find(t=>t.id===d).focusDay,null);assert.match(await js('document.querySelector("#toast").textContent'),/最多/);
 const drag=async(id,selector)=>js(`(()=>{const dt=new DataTransfer();document.querySelector('[data-task="${id}"]').dispatchEvent(new DragEvent('dragstart',{bubbles:true,dataTransfer:dt}));document.querySelector(${JSON.stringify(selector)}).dispatchEvent(new DragEvent('drop',{bubbles:true,cancelable:true,dataTransfer:dt}));})()`);
 await drag(c,`[data-task="${a}"]`);await until(()=>js(`document.querySelector('.focus-grid .task').dataset.task === '${c}'`),'reorder');
 await drag(c,'[data-focus-drop="false"]');await until(()=>Promise.resolve(!s.state.tasks.find(t=>t.id===c).focusDay),'demote');
 await js('document.body.click()');await sleep(150);
 const shots=path.resolve(__dirname,'../../');
 async function shot(name){await sleep(150);fs.writeFileSync(path.join(shots,name),(await win.webContents.capturePage()).toPNG());}
 await shot('日序-今天.png');
 await call('settings',{view:'week'});await until(()=>js('document.querySelectorAll(".week-lane").length===7'),'week');
 assert.equal(await js('document.querySelectorAll(".overloaded").length'),1);
 await drag(a,`[data-schedule="${days[1]}"]`);await until(()=>Promise.resolve(s.state.tasks.find(t=>t.id===a).plannedDate===days[1]),'schedule drop');assert.equal(s.state.tasks.find(t=>t.id===a).due,due);
 await shot('日序-本周.png');
 await call('settings',{view:'inbox'});await until(()=>js('document.querySelectorAll(".inbox-list .task").length===2'),'inbox');
 assert.ok(globalShortcut.isRegistered(s.state.settings.quickShortcut),'OS global shortcut registered');
 await runtime.showQuickCapture();const q=runtime.getQuickWindow();await until(()=>Promise.resolve(q.isVisible()),'quick visible');
 await q.webContents.executeJavaScript(`document.querySelector('#quick-title').value='从快捷输入记录';document.querySelector('#capture').requestSubmit();`,true);
 await until(()=>Promise.resolve(!q.isVisible()),'capture hides');assert.equal(s.state.tasks.at(-1).title,'从快捷输入记录');assert.equal(s.state.tasks.at(-1).inbox,true);
 const unauthorized=await q.webContents.executeJavaScript(`window.fourfold.call('state').then(()=>'accepted').catch(()=> 'denied')`,true);assert.equal(unauthorized,'denied');
 await shot('日序-收集箱.png');
 await call('current',{id:b});await call('window:compact',{enabled:true});assert.equal(win.isAlwaysOnTop(),true);assert.deepEqual(win.getSize(),[390,320]);
 await until(()=>js('document.querySelectorAll(".compact-task").length===3'),'compact queue');assert.equal(await js('document.querySelector(".current-task .task-title").textContent'),'阅读一章书');
 await shot('日序-置顶小窗.png');await call('window:compact',{enabled:false});assert.deepEqual(win.getSize(),[960,640]);
 await call('settings',{view:'quadrants',calendarOpen:true});await shot('日序-四象限.png');
 const colors=await js('[...document.querySelectorAll(".zone-heading h2")].map(e=>getComputedStyle(e).color)');assert.equal(new Set(colors).size,4);
 await call('settings',{transparency:100,textTransparency:0});
 assert.equal(await js('getComputedStyle(document.querySelector("#app")).backgroundColor'),'rgba(246, 249, 245, 0)');
 const backgrounds=await js('[...document.querySelectorAll(".zone,.task")].map(e=>getComputedStyle(e).backgroundColor)');assert.ok(backgrounds.every(x=>x==='rgba(0, 0, 0, 0)'||x.endsWith(', 0)')||x.endsWith('/ 0)')),JSON.stringify(backgrounds));
 assert.equal(await js('getComputedStyle(document.querySelector(".task-top")).opacity'),'1');
 await call('settings',{textTransparency:65});assert.equal(await js('getComputedStyle(document.querySelector(".task-top")).opacity'),'0.35');assert.equal(await js('getComputedStyle(document.querySelector(".toolbar")).opacity'),'1');
 await call('settings',{transparency:35,textTransparency:0});
 await js(`document.querySelector('[data-review="${late}"]').click()`);await until(()=>js('document.querySelector("#review-dialog").open'),'review');
 await js('document.querySelector("[data-review-choice=keep]").click()');await until(()=>js('!document.querySelector("#review-dialog").open'),'keep');assert.equal(s.state.tasks.find(t=>t.id===late).status,'active');
 await js(`document.querySelector('[data-review="${late}"]').click()`);await until(()=>js('document.querySelector("#review-dialog").open'),'review cancel');await js('document.querySelector("[data-review-choice=cancel]").click()');await until(()=>Promise.resolve(s.state.tasks.find(t=>t.id===late).status==='cancelled'),'cancel');
 await call('undo');assert.equal(s.state.tasks.find(t=>t.id===late).status,'active');
 await call('settings',{theme:'dark',view:'today',calendarOpen:false});await shot('日序-深色.png');
 await call('settings',{theme:'system'}); win.webContents.debugger.attach('1.3'); await win.webContents.debugger.sendCommand('Emulation.setEmulatedMedia',{features:[{name:'prefers-color-scheme',value:'dark'}]}); assert.equal(await js('getComputedStyle(document.documentElement).getPropertyValue("--surface-rgb").trim()'),'30,48,40'); win.webContents.debugger.detach();
 assert.deepEqual(errors,[]);
 const restored=new Store(s.directory);assert.equal(restored.state.schemaVersion,2);assert.equal(restored.state.tasks.at(-1).title,'从快捷输入记录');
 console.log(JSON.stringify({passed:true,directory:dir,checks:['top3 limit','drag reorder/demote','week independent deadline','overload indicator','global shortcut registration','quick capture save/hide','quick window IPC restrictions','compact size/always-on-top/queue','four distinct colors','100% transparent surfaces','independent text opacity','keep/cancel/undo','schema 2 persistence','screenshots/no renderer errors']}));app.quit();
})().catch(e=>{console.error(e);app.exit(1);});
