'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const {apply}=require('../src/update-helper.cjs');
const {installTarget,prepareInstall,extractLinux}=require('../src/update-installer.cjs');
function fixture(t){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'rixu-install-test-'));t.after(()=>fs.rmSync(dir,{recursive:true,force:true}));const root=path.join(dir,'app'),stage=path.join(dir,'stage'),prepared=path.join(stage,'app');fs.mkdirSync(root);fs.mkdirSync(prepared,{recursive:true});fs.writeFileSync(path.join(root,'version'),'old');fs.writeFileSync(path.join(prepared,'version'),'new');return {kind:'local',root,stage,prepared,backup:path.join(dir,'backup'),result:path.join(dir,'result.json'),executable:path.join(root,'rixu')};}
test('helper replaces app only after parent exits and retains old runtime',async t=>{const p=fixture(t);let exited=false;await apply(p,{wait:async()=>{assert.equal(fs.readFileSync(path.join(p.root,'version'),'utf8'),'old');exited=true;},launch:async()=>{assert.ok(exited);assert.equal(fs.readFileSync(path.join(p.root,'version'),'utf8'),'new');}});assert.equal(fs.readFileSync(path.join(p.backup,'version'),'utf8'),'old');assert.equal(JSON.parse(fs.readFileSync(p.result)).ok,true);});
test('failed new launch restores old runtime and restarts it',async t=>{const p=fixture(t);let launches=0;await assert.rejects(apply(p,{wait:async()=>{},launch:async()=>{if(++launches===1)throw Error('launch failed');assert.equal(fs.readFileSync(path.join(p.root,'version'),'utf8'),'old');}}));assert.equal(launches,2);assert.equal(JSON.parse(fs.readFileSync(p.result)).ok,false);});
test('parent exit failure leaves installation untouched',async t=>{const p=fixture(t);await assert.rejects(apply(p,{wait:async()=>{throw Error('still running');}}));assert.equal(fs.readFileSync(path.join(p.root,'version'),'utf8'),'old');});
test('installation rejects mismatched metadata and transient macOS volume',async()=>{assert.equal(installTarget({platform:'darwin',execPath:'/Volumes/Rixu/日序.app/Contents/MacOS/rixu',packaged:true}).kind,'unsupported');await assert.rejects(prepareInstall({candidate:{kind:'deb',file:'x',version:'1.0.7'},target:{kind:'deb'},command:async()=>({stdout:'Package: malicious-rixu\nVersion: 11.0.7'})}),/标识/);});
test('archive extraction rejects symbolic links outside staging',async t=>{const p=fixture(t),dir=path.dirname(p.root),prefix='Rixu-1.0.7-linux-x64';fs.mkdirSync(path.join(dir,prefix));fs.symlinkSync('/tmp',path.join(dir,prefix,'escape'));const archive=path.join(dir,'bad.tar.gz');await require('tar').c({gzip:true,file:archive,cwd:dir},[prefix]);await assert.rejects(extractLinux(archive,p.stage,'1.0.7'),/内容无效/);});
