'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const {apply}=require('../src/update-helper.cjs');
const {installTarget,prepareInstall,extractLinux}=require('../src/update-installer.cjs');
function fixture(t){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'rixu-install-test-'));t.after(()=>fs.rmSync(dir,{recursive:true,force:true}));const root=path.join(dir,'app'),stage=path.join(dir,'stage'),prepared=path.join(stage,'app');fs.mkdirSync(root);fs.mkdirSync(prepared,{recursive:true});fs.writeFileSync(path.join(root,'version'),'old');fs.writeFileSync(path.join(prepared,'version'),'new');return {kind:'local',root,stage,prepared,backup:path.join(dir,'backup'),result:path.join(dir,'result.json'),executable:path.join(root,'rixu')};}
test('helper replaces app only after parent exits and retains old runtime',async t=>{const p=fixture(t);let exited=false;await apply(p,{wait:async()=>{assert.equal(fs.readFileSync(path.join(p.root,'version'),'utf8'),'old');exited=true;},launch:async()=>{assert.ok(exited);assert.equal(fs.readFileSync(path.join(p.root,'version'),'utf8'),'new');}});assert.equal(fs.readFileSync(path.join(p.backup,'version'),'utf8'),'old');assert.equal(JSON.parse(fs.readFileSync(p.result)).ok,true);});
test('failed new launch restores old runtime and restarts it',async t=>{const p=fixture(t);let launches=0;await assert.rejects(apply(p,{wait:async()=>{},launch:async()=>{if(++launches===1)throw Error('launch failed');assert.equal(fs.readFileSync(path.join(p.root,'version'),'utf8'),'old');}}));assert.equal(launches,2);assert.equal(JSON.parse(fs.readFileSync(p.result)).ok,false);});
test('parent exit failure leaves installation untouched',async t=>{const p=fixture(t);await assert.rejects(apply(p,{wait:async()=>{throw Error('still running');}}));assert.equal(fs.readFileSync(path.join(p.root,'version'),'utf8'),'old');});
test('installation rejects mismatched metadata and transient macOS volume',async()=>{assert.equal(installTarget({platform:'darwin',execPath:'/Volumes/Rixu/日序.app/Contents/MacOS/rixu',packaged:true}).kind,'unsupported');await assert.rejects(prepareInstall({candidate:{kind:'deb',file:'x',version:'1.0.7'},target:{kind:'deb'},command:async()=>({stdout:'Package: malicious-rixu\nVersion: 11.0.7'})}),/标识/);});
test('archive extraction rejects symbolic links outside staging',async t=>{const p=fixture(t),dir=path.dirname(p.root),prefix='Rixu-1.0.7-linux-x64';fs.mkdirSync(path.join(dir,prefix));fs.symlinkSync('/tmp',path.join(dir,prefix,'escape'));const archive=path.join(dir,'bad.tar.gz');await require('tar').c({gzip:true,file:archive,cwd:dir},[prefix]);await assert.rejects(extractLinux(archive,p.stage,'1.0.7'),/内容无效/);});
test('system deb install success and cancellation both restart without discarding tasks',async t=>{const p=fixture(t);p.kind='deb';p.file='/tmp/Rixu.deb';for(const failed of [false,true]){let restarted=false;await apply(p,{wait:async()=>{},execFile:(command,args,done)=>{assert.equal(command,'pkexec');assert.deepEqual(args,['dpkg','-i',p.file]);done(failed?Error('cancelled'):null);},launch:async()=>{restarted=true;}});assert.equal(restarted,true);assert.equal(JSON.parse(fs.readFileSync(p.result)).ok,!failed);assert.equal(fs.readFileSync(path.join(p.root,'version'),'utf8'),'old');}});
test('Windows install plan retains the original directory and excludes quoted NSIS destination',async()=>{const target=installTarget({platform:'win32',execPath:'C:\\Users\\Name\\Programs\\日序\\rixu.exe',packaged:true});assert.equal(target.root,'C:\\Users\\Name\\Programs\\日序');const plan=await prepareInstall({candidate:{kind:'nsis',file:'update.exe'},target});assert.equal(plan.executable,target.executable);const source=require('../src/update-windows.cjs').windowsCommand("C:\\User's files\\plan.json");assert.match(source,/User''s files/);assert.match(source,/\/D=' \+ \$plan.root/);assert.doesNotMatch(source,/--force-run/);});
test('Windows helper starts with Unicode paths and reports an installer failure', {skip:process.platform!=='win32'},async t=>{
 const directory=fs.mkdtempSync(path.join(os.tmpdir(),'日序 update-'));t.after(()=>fs.rmSync(directory,{recursive:true,force:true}));
 try{await require('../src/update-installer.cjs').launchInstall({directory,parentPid:2147483647,plan:{kind:'nsis',file:path.join(directory,'missing.exe'),root:directory,executable:path.join(process.env.SystemRoot,'System32','where.exe')}});
 for(let i=0;i<100&&!fs.existsSync(path.join(directory,'install-result.json'));i++)await new Promise(r=>setTimeout(r,50));
 assert.equal(JSON.parse(fs.readFileSync(path.join(directory,'install-result.json'),'utf8')).ok,false);
 }catch(error){console.error(fs.readFileSync(path.join(directory,'install.log'),'utf8'));console.error('Result created:',fs.existsSync(path.join(directory,'install-result.json')));const probe=require('node:child_process').spawnSync(path.join(process.env.SystemRoot,'System32','WindowsPowerShell','v1.0','powershell.exe'),['-NoProfile','-NonInteractive','-Command','Write-Output READY'],{encoding:'utf8',windowsHide:true});console.error('PowerShell probe:',probe.status,probe.stdout,probe.stderr);throw error;}
});
